project:
  type: website
  output-dir: docs

website:
  title: "VKM NDFs for Tortoises - R Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Search strategy
      - Get_OA.qmd
      - icon: github
        href: https://github.com/DrMattG/Tortoise_NDFs
      
format:
  html:
    theme:
      light: [cosmo, style/dsbox.scss]
      # dark: [cosmo, style/dsbox.scss, style/dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    # mainfont: "Atkinson Hyperlegible"
    # include-in-header: "style/fontawesome.html"
        
editor: visual