website:
  title: "VKM NDFs for Tortoises - R Documentation"
  navbar:
    right:
      - href: index.qmd
        text: Search strategy
      - Get_OA.qmd
        
format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual